### ISSUE TITLE
Invalid results

### ISSUE THREAD

**Issue by zdm** [rsimoes/Mozilla-PublicSuffix#7]
For www.aport.co.uk it returns aport.co.uk but should return co.uk.

I do not test with other domains.

Best.

**Comment by rsimoes** [comment]
Are you able to provide the version you're running? I'm not getting the same result.

```bash
~ perl -MMozilla::PublicSuffix=public_suffix -E 'say public_suffix("www.aport.co.uk")'
co.uk
```

**Comment by zdm** [comment]
Hi.

Hmm, now I get right results.

Maybe this was error on my side.

Please, close issue.

Sorry.
